name: Publish Image
on:
  workflow_dispatch: # Only manual trigger and only for the main branch
    branches:
      - main
env:
  IMAGE_NAME: unity-catalog
  VERSION: 0.1.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB}}

    - name: Publish
      run: |
        # Docker build
        docker build -t "${{ env.IMAGE_NAME }}:dev" .
        docker tag "${{ env.IMAGE_NAME }}:dev" "godatadriven/${{ env.IMAGE_NAME }}:dev"
        docker tag "${{ env.IMAGE_NAME }}:dev" "godatadriven/${{ env.IMAGE_NAME }}:${env.VERSION}"
        docker push "godatadriven/${{ env.IMAGE_NAME }}:dev"
        docker push "godatadriven/${{ env.IMAGE_NAME }}:${env.VERSION}"