name: Publish Image
on:
  workflow_dispatch: # Only manual trigger and only for the main branch
    branches:
      - main
env:
  IMAGE_NAME: unity-catalog
  VERSION: 0.1.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Prepare
      id: prep
      run: |
        echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image
      uses: docker/build-push-action@v4
      with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}

    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB}}

    - name: Push image
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v4
      with:
          context: .
          file: ./Dockerfile
          push: true
          provenance: false
          sbom: false
          tags: |
            godatadriven/${{ env.IMAGE_NAME }}:${env.VERSION}
            godatadriven/${{ env.IMAGE_NAME }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          platforms: linux/amd64,linux/arm64