name: Publish Image
on:
  workflow_dispatch:
    branches:
      - main
env:
  IMAGE_NAME: unity-catalog

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB }}
        repository: godatadriven/${{ env.IMAGE_NAME }}